version: 3.x

services:
  mysql:
    image: biarms/mysql:5.7
    environment:
      MYSQL_DATABASE: dbunit
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3406:3306'

  php:
    build:
      context: .
      dockerfile: Dockerfile.php8.3
    volumes:
      - .:/usr/src/myapp
