FROM php:8.4-cli

RUN apt-get update \
  && apt-get -y install --no-install-recommends \
    git unzip libpq-dev
    
RUN docker-php-ext-install pdo_mysql pgsql pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /usr/src/myapp
